apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: notification-service
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: notification-service
  template:
    metadata:
      labels:
        io.kompose.service: notification-service
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: Clerk:Authority
              valueFrom:
                secretKeyRef:
                  name: projeli-secrets
                  key: clerk-authority
            - name: Clerk:AuthorizedParty
              valueFrom:
                secretKeyRef:
                  name: projeli-secrets
                  key: clerk-authorized-party
            - name: Database:WriteConnectionString
              valueFrom:
                secretKeyRef:
                  name: projeli-secrets
                  key: postgres-connection-string
            - name: Database:ReadConnectionString
              valueFrom:
                secretKeyRef:
                  name: projeli-secrets
                  key: postgres-connection-string
            - name: ENV
              value: development
            - name: RabbitMQ:Host
              value: rabbitmq
            - name: RabbitMQ:Username
              valueFrom:
                secretKeyRef:
                  name: projeli-secrets
                  key: rabbitmq-username
            - name: RabbitMQ:Password
              valueFrom:
                secretKeyRef:
                  name: projeli-secrets
                  key: rabbitmq-password
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://prometheus
          image: daqem/projeli:notification
          name: notification-service
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
