apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: project-service
  name: project-service
spec:
  ports:
    - name: "5002"
      port: 5002
      targetPort: 80
  selector:
    io.kompose.service: project-service
