apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yaml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: 'project-service'
        kubernetes_sd_configs:
          - role: service
            namespaces:
              names:
                - default
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: project-service
          - source_labels: [__meta_kubernetes_service_port_number]
            action: keep
            regex: 5002
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
      - job_name: 'wiki-service'
        kubernetes_sd_configs:
          - role: service
            namespaces:
              names:
                - default
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: wiki-service
          - source_labels: [__meta_kubernetes_service_port_number]
            action: keep
            regex: 5003
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
      - job_name: 'user-service'
        static_configs:
          - targets: ['user-service:5001']