apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: storage-service
  name: storage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: storage-service
  template:
    metadata:
      labels:
        io.kompose.service: storage-service
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: Clerk:Authority
              valueFrom:
                secretKeyRef:
                  name: projeli-secrets
                  key: clerk-authority
            - name: Clerk:AuthorizedParty
              valueFrom:
                secretKeyRef:
                  name: projeli-secrets
                  key: clerk-authorized-party
            - name: ENV
              value: development
            - name: RabbitMQ:Host
              value: rabbitmq
            - name: RabbitMQ:Username
              valueFrom:
                secretKeyRef:
                  name: projeli-secrets
                  key: rabbitmq-username
            - name: RabbitMQ:Password
              valueFrom:
                secretKeyRef:
                  name: projeli-secrets
                  key: rabbitmq-password
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://prometheus
            - name: AWS:AccessKey
              valueFrom:
                secretKeyRef:
                  name: projeli-secrets
                  key: aws-access-key
            - name: AWS:SecretKey
              valueFrom:
                secretKeyRef:
                  name: projeli-secrets
                  key: aws-secret-key
            - name: AWS:ServiceUrl
              valueFrom:
                secretKeyRef:
                  name: projeli-secrets
                  key: aws-service-url
            - name: AWS:BucketName
              valueFrom:
                secretKeyRef:
                  name: projeli-secrets
                  key: aws-bucket-name
          image: daqem/projeli:storage
          name: storage-service
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
