apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ui
  template:
    metadata:
      labels:
        io.kompose.service: ui
    spec:
      containers:
        - env:
            - name: CLERK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: projeli-secrets
                  key: clerk-secret-key
            - name: GATEWAY_URL
              value: http://api-gateway:5000
          image: daqem/projeli:ui
          name: ui
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: "500m"      # Requests 0.5 core
              memory: "1Gi"    # Requests 1 GiB of memory
            limits:
              cpu: "1"         # Can scale up to 1 core
              memory: "2Gi"    # Can use up to 2 GiB of memory
      restartPolicy: Always
