apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  template:
    metadata:
      labels:
        io.kompose.service: user-service
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: Clerk:Authority
              valueFrom:
                secretKeyRef:
                  name: projeli-secrets
                  key: clerk-authority
            - name: Clerk:AuthorizedParty
              valueFrom:
                secretKeyRef:
                  name: projeli-secrets
                  key: clerk-authorized-party
            - name: Clerk:SecretKey
              valueFrom:
                secretKeyRef:
                  name: projeli-secrets
                  key: clerk-secret-key
            - name: ENV
              value: development
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://prometheus
          image: daqem/projeli:user
          name: user-service
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
