apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: wiki-service
  name: wiki-service
spec:
  ports:
    - name: "5003"
      port: 5003
      targetPort: 80
  selector:
    io.kompose.service: wiki-service
